HW/HW/HW/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('schedule/', include('schedule.urls')),
    path('admin/', admin.site.urls),
]

HW/HW/schedule/urls.py
from django.urls import path
from . import views

app_name = 'schedule'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:group_id>/', views.detail_student, name='detail_student'),
    path('<str:name>/', views.detail_lecturer, name='detail_lecturer')
]

HW/HW/schedule/models.py
from django.db import models


class Exam(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    lecturer = models.CharField(max_length=50, verbose_name='Преподаватель')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Экзамен'
        verbose_name_plural = 'Экзамены'
        ordering = ['name']


class Group(models.Model):
    name = models.CharField(max_length=50, verbose_name='Номер')
    lessons = models.ManyToManyField(Exam, through='Schedule')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'
        ordering = ['name']


class Schedule(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='Группа')
    lesson = models.ForeignKey(Exam, on_delete=models.CASCADE, verbose_name='Экзамен')
    lesson_time = models.DateTimeField(default='2021-01-10', verbose_name='Время экзамена')
    consultation_time = models.DateTimeField(default='2021-01-10', verbose_name='Время консультации')

    class Meta:
        verbose_name = 'Расписание'
        verbose_name_plural = 'Расписание'
        ordering = ['group']

HW/HW/schedule/views.py
from django.shortcuts import get_list_or_404, render
from django.http import HttpResponseRedirect
from django.template import loader
from .models import Exam, Group, Schedule


def index(request):
    group_list = Group.objects.all()
    exam_list = Exam.objects.all()
    context = {'group_list': group_list, 'exam_list': exam_list}
    return render(request, 'schedule/index.html', context)


def detail_student(request, group_id):
    group_list = Group.objects.all()
    for i in group_list:
        if i.id == group_id:
            group = i
    schedule_list = get_list_or_404(Schedule, group=group_id)
    for i in range(len(schedule_list) - 1):
        for j in range(len(schedule_list) - i - 1):
            if schedule_list[j].lesson_time > schedule_list[j + 1].lesson_time:
                schedule_list[j], schedule_list[j + 1] = schedule_list[j + 1], schedule_list[j]
    exam_list = []
    for i in schedule_list:
        exam_list.append(i.lesson)
    # for exam in exam_list:
    return render(request, 'schedule/detail_student.html', {'group': group,
                                                            'schedule_list': schedule_list,
                                                            'exam_list': exam_list})


def detail_lecturer(request, name):
    exam_list = Exam.objects.all()
    for i in exam_list:
        if i.lecturer == name:
            exam = i
    schedule_list = get_list_or_404(Schedule, lesson=exam)
    for i in range(len(schedule_list) - 1):
        for j in range(len(schedule_list) - i - 1):
            if schedule_list[j].lesson_time > schedule_list[j + 1].lesson_time:
                schedule_list[j], schedule_list[j + 1] = schedule_list[j + 1], schedule_list[j]
    group_list = []
    for i in schedule_list:
        group_list.append(i.group)

    # формируем листы дат консультаций и экзаменов
    # а также формируем листы количества консультаций и экзаменов в датологическом порядке
    schedule_exam_data_list = []
    schedule_cons_data_list = []
    count_ex = 1
    count_cons = 1
    cons_count = [1]
    exam_count = [1]
    for schedule in schedule_list:
        current_exam_date_str = str(schedule.lesson_time)
        current_cons_date_str = str(schedule.consultation_time)
        current_exam_date = current_exam_date_str.split(' ')
        current_cons_date = current_cons_date_str.split(' ')
        if len(schedule_exam_data_list) != 0:
            if current_exam_date[0] == schedule_exam_data_list[-1]:
                exam_count[-1] += 1
            else:
                exam_count.append(count_ex)
                count_ex = 1
                schedule_exam_data_list.append(current_exam_date[0])
        else:
            schedule_exam_data_list.append(current_exam_date[0])
        if len(schedule_cons_data_list) != 0:
            if current_cons_date[0] == schedule_cons_data_list[-1]:
                cons_count[-1] += 1
            else:
                cons_count.append(count_cons)
                count_cons = 1
                schedule_cons_data_list.append(current_cons_date[0])
        else:
            schedule_cons_data_list.append(current_cons_date[0])

    # создаем полный лист дат для графика
    schedule_data_list = []
    i = j = 0
    while (i < len(schedule_exam_data_list)) and (j < len(schedule_cons_data_list)):
        if schedule_exam_data_list[i] < schedule_cons_data_list[j]:
            schedule_data_list.append(schedule_exam_data_list[i])
            i += 1
        else:
            schedule_data_list.append(schedule_cons_data_list[j])
            j += 1
    while i < len(schedule_exam_data_list):
        schedule_data_list.append(schedule_exam_data_list[i])
        i += 1
    while j < len(schedule_cons_data_list):
        schedule_data_list.append(schedule_cons_data_list[j])
        j += 1

    # определяем кол-во консультаций и экзаменов в каждую из дат
    i = 0
    for i in range(len(schedule_data_list)):
        if schedule_data_list[i] not in schedule_exam_data_list:
            j = 0
            for date in schedule_exam_data_list:
                if schedule_data_list[i] < date:
                    schedule_exam_data_list.append('0')
                    k = len(schedule_exam_data_list) - 2
                    while k >= j:
                        schedule_exam_data_list[k + 1] = schedule_exam_data_list[k]
                        k -= 1
                    schedule_exam_data_list[j] = schedule_data_list[i]
                    break
                else:
                    j += 1
            exam_count.append(0)
            k = len(exam_count) - 2
            while k >= j:
                exam_count[k + 1] = exam_count[k]
                k -= 1
            exam_count[j] = 0
        i += 2
    i = 1
    for i in range(len(schedule_data_list)):
        if schedule_data_list[i] not in schedule_cons_data_list:
            j = 0
            for date in schedule_cons_data_list:
                if schedule_data_list[i] < date:
                    schedule_cons_data_list.append('0')
                    k = len(schedule_cons_data_list) - 2
                    while k >= j:
                        schedule_cons_data_list[k + 1] = schedule_cons_data_list[k]
                        k -= 1
                    schedule_cons_data_list[j] = schedule_data_list[i]
                    break
                else:
                    j += 1
            cons_count.append(0)
            k = len(cons_count) - 2
            while k >= j:
                cons_count[k + 1] = cons_count[k]
                k -= 1
            cons_count[j] = 0
        i += 2

    # убираем повторные даты
    i = 0
    schedule_data_list_no_repetitions = []
    for i in range(len(schedule_data_list) - 1):
        if schedule_data_list[i] != schedule_data_list[i + 1]:
            schedule_data_list_no_repetitions.append(schedule_data_list[i])
            if i == len(schedule_data_list) - 2:
                schedule_data_list_no_repetitions.append(schedule_data_list[i + 1])
            i += 1
            continue

    if request.method == "POST":
        exam.name = request.POST.get("exam_name")
        exam.save()
        name_group_change = request.POST.get("group_name")
        for group in group_list:
            if group.name == name_group_change:
                group_change = group
                break
        for schedule in schedule_list:
            if schedule.group == group_change:
                schedule.lesson_time = request.POST.get("lesson_time")
                schedule.consultation_time = request.POST.get("consultation_time")
                schedule.save()
        return HttpResponseRedirect(f"/schedule/{name}")
    else:
        return render(request, 'schedule/detail_lecturer.html', {'group_list': group_list,
                                                                 'schedule_list': schedule_list,
                                                                 'exam': exam,
                                                                 'schedule_date_list': schedule_data_list_no_repetitions,
                                                                 'exam_count': exam_count,
                                                                 'cons_count': cons_count})

HW/HW/schedule/templates/schedule/detail_lecturer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail for lecturer</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/941547f2e9.js" crossorigin="anonymous"></script>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'schedule/css/style.css' %}">
    <link href="{% static 'schedule/css/c3.min.css' %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid modal-header">
            <div>
                <a class="navbar-brand" href="/schedule/"><i class="fas fa-reply text-light navbar-brand"></i>Назад</a>
            </div>
            <div class="float-end">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#signUpModal">
                    Внести изменения
                </button>

                <!-- Modal -->
                <div class="modal fade" id="signUpModal" tabindex="-1" aria-labelledby="signUpModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="signUpModalLabel">Внести изменения</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form class="g-3 needs-validation signup" method="post" novalidate>
                                    {% csrf_token %}
                                    <label for="validationCustom01" class="form-label">Название предмета</label>
                                    <input type="text" class="form-control" id="validationCustom01" value="{{ exam.name }}" name="exam_name" required>
                                    <div class="invalid-feedback">
                                        Пожалуйста введите название предмета
                                    </div>
                                    <p></p>
                                    <label for="validationCustom02" class="form-label">Группа</label>
                                    <select class="form-select" id="validationCustom02" value="{{ group.name }}" name="group_name" required>
                                        <option selected disabled value="">Выберите...</option>
                                        {% for i in group_list %}
                                            <option>{{ i }}</option>
                                        {% endfor %}
                                    </select>
                                    <div class="invalid-feedback">
                                        Пожалуйста выберите группу
                                    </div>
                                    <p></p>
                                    <label for="validationCustom03" class="form-label">Время консультации</label>
                                    <input type="datetime-local" class="form-control" id="validationCustom03" value="{{ schedule.consultation_time }}" name="consultation_time" required>
                                    <div class="invalid-feedback">
                                        Пожалуйста выберите время консультации
                                    </div>
                                    <p></p>
                                    <label for="validationCustom04" class="form-label">Время экзамена</label>
                                    <input type="datetime-local" class="form-control" id="validationCustom04" value="{{ schedule.lesson_time }}" name="lesson_time" required>
                                    <div class="invalid-feedback">
                                        Пожалуйста выберите время экзамена
                                    </div>
                                    <p></p>
                                    <div class="modal-footer">
                                        <input class = "btn btn-success" type="submit" value="Save" name="_save">
                                        <button class="btn btn-danger" type="button" data-dismiss="modal">Close</button>
                                    </div>
                                    <script>
                                        // JavaScript for disabling form submissions if there are invalid fields
                                        (function () {
                                            'use strict'

                                            // Fetch all the forms we want to apply custom Bootstrap validation styles to
                                            var forms = document.querySelectorAll('.needs-validation')

                                            // Loop over them and prevent submission
                                            Array.prototype.slice.call(forms)
                                                .forEach(function (form) {
                                                    form.addEventListener('submit', function (event) {
                                                        if (!form.checkValidity()) {
                                                            event.preventDefault()
                                                            event.stopPropagation()
                                                        }

                                                        form.classList.add('was-validated')
                                                    }, false)
                                                })
                                        })()
                                    </script>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <main class="container-fluid bg-dark">
        <div class="row">
            <div class="col-6">
                <h1 class="text-light">{{ exam.name }}</h1>
                <h2 class="text-light">{{ exam.lecturer }}</h2>
                <table class="table table-dark table-borderless table-striped">
                    <tr>
                        <th class="text-center">Группа</th>
                        <th class="text-center">Консультация</th>
                        <th class="text-center">Экзамен</th>
                    </tr>
                    {% for group in group_list %}
                        <tr>
                            <td class="text-center">{{ group.name }}</td>
                            {% for schedule in schedule_list %}
                                {% if schedule.group == group %}
                                    <td class="text-center">{{ schedule.consultation_time|date:'d-m-Y H:i' }}</td>
                                    <td class="text-center">{{ schedule.lesson_time|date:'d-m-Y H:i' }}</td>
                                {% endif %}
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="col-5" id="chart"></div>
        </div>
    </div>
    </main>
    <footer class="high bg-dark">
    </footer>

    <script src="https://d3js.org/d3.v5.min.js"></script>
    <script src="{% static 'schedule/js/c3.min.js' %}"></script>

    <script>
        var chart = c3.generate({
        data: {
            size: {
                width: 400
            },
            x: 'x',
            columns: [
                ['x', "{{ schedule_date_list.0 }}", "{{ schedule_date_list.1 }}", "{{ schedule_date_list.2 }}", "{{ schedule_date_list.3 }}", "{{ schedule_date_list.4 }}", "{{ schedule_date_list.5 }}", "{{ schedule_date_list.6 }}", "{{ schedule_date_list.7 }}", "{{ schedule_date_list.8 }}", "{{ schedule_date_list.9 }}"],
                ['Количество экзаменов', "{{ exam_count.0 }}", "{{ exam_count.1 }}", "{{ exam_count.2 }}", "{{ exam_count.3 }}", "{{ exam_count.4 }}", "{{ exam_count.5 }}", "{{ exam_count.6 }}", "{{ exam_count.7 }}", "{{ exam_count.8 }}", "{{ exam_count.9 }}"],
                ['Количество консультаций', "{{ cons_count.0 }}", "{{ cons_count.1 }}", "{{ cons_count.2 }}", "{{ cons_count.3 }}", "{{ cons_count.4 }}", "{{ cons_count.5 }}", "{{ cons_count.6 }}", "{{ cons_count.7 }}", "{{ cons_count.8 }}", "{{ cons_count.9 }}"]
            ],
            type: 'bar',
            groups: [
            ['Количество экзаменов', 'Количество консультаций']
        ]
        },
        bar: {
            width: {
                ratio: 0.5
            }
        },
        axis: {
            x: {
                type: 'timeseries',
                tick: {
                    format: '%d-%m'
                }
            },
            y: {
                max: 3,
                min: 0,
            }
        },
        color: {
            pattern: ['#ca4141', '#40bcbc']
        }
    });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
</body>
</html>

HW/HW/schedule/templates/schedule/detail_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail for student</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/941547f2e9.js" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'schedule/css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid modal-header">
            <div>
                <a class="navbar-brand" href="/schedule/"><i class="fas fa-reply text-light navbar-brand"></i>Назад</a>
            </div>
        </div>
    </nav>
    <main class="container-fluid bg-dark">
        <div class="row justify-content-around">
            <div class="col-6">
                <h1 class="text-center text-light">{{ group.name }}</h1>
                <table class="table table-dark table-borderless table-striped">
                    <tr>
                        <th class="text-center">Экзамен</th>
                        <th class="text-center">Консультация</th>
                        <th class="text-center">Экзамен</th>
                        <th class="text-center">Преподаватель</th>
                    </tr>
                    {% for exam in exam_list %}
                        <tr>
                            <td class="text-center">{{ exam.name }}</td>
                            {% for schedule in schedule_list %}
                                {% if schedule.lesson == exam %}
                                    <td class="text-center"><time datetime="">{{ schedule.consultation_time|date:'d-m-Y H:i' }}</time></td>
                                    <td class="text-center">{{ schedule.lesson_time|date:'d-m-Y H:i' }}</td>
                                {% endif %}
                            {% endfor %}
                            <td class="text-center">{{ exam.lecturer }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </main>
    <footer class="high bg-dark">
    </footer>
</body>
</html>

HW/HW/schedule/templates/schedule/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Schedule</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'schedule/css/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid modal-header">
            <a class="navbar-brand" href="/schedule/">
<!--                <img src="{% static "schedule/images/BMSTU_logo.png" %}" alt="BMSTU logo" width="70" height="70" class="img-fluid">-->
                <h3>Расписание экзаменов</h3>
            </a>
            <div class="float-end">
                <div class="justify-content-center">
                    <table>
                        <tr>
                            <td class="text-center">
                                <img class="img-fluid" src="{% static "schedule/images/BMSTU_logo.png" %}" alt="BMSTU logo" width="50" height="50">
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">
                                <p class="text-light">МГТУ им. Н.Э. Баумана</p>
                            </td>

                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </nav>

    <main class="container-fluid bg-dark">
        <div class="row">
            <div class="col-2">
                <div class="card text-white bg-dark">
                    <div class="card-header">
                        <h4>Группы</h4>
                    </div>
                    {% if group_list %}
                        <ul class="list-group list-group-flush">
                            {% for group in group_list %}
                                <li class="list-group-item bg-dark">
                                    <a class="list" href="{% url 'schedule:detail_student' group.id %}"><h5>{{ group.name }}</h5></a>
                                </li>
                            {% endfor %}
                    </ul>
                    {% else %}
                        <p>No group are available.</p>
                    {% endif %}
                </div>
            </div>
            <div class="col-3">
                <div class="card text-white bg-dark">
                    <div class="card-header">
                        <h4>Преподаватели</h4>
                    </div>
                    {% if exam_list %}
                        <ul class="list-group list-group-flush">
                            {% for exam in exam_list %}
                                <li class="list-group-item bg-dark">
                                    <a class="list" href="{% url 'schedule:detail_lecturer' exam.lecturer %}"><h5>{{ exam.lecturer }}</h5></a>
                                </li>
                            {% endfor %}
                    </ul>
                    {% else %}
                        <p>No lecturer are available.</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="container-fluid high">

        </div>
    </main>

    <footer class="modal-footer bg-dark">
        <address class="container-fluid">
            <p style="color: #d3d3d4">Контакты: +7-(922)-724-47-88</p>
        </address>
        <p class="container-fluid text-center" style="color: #d3d3d4">2020 BMSTU</p>
    </footer>
</body>
</html>